In [71]:
import numpy as np

In [2]:
#线性代数

In [3]:
x = np.array([[1., 2., 3.],[4., 5., 6.]])

In [4]:
y = np.array([[6., 23.],[-1., 7],[8, 9]])

In [5]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [7]:
x.dot(y)      #dot()矩阵点乘，等价于np.dot(x, y)
#所得到的数组中的每个元素为，第一个矩阵中与该元素行号相同的元素与第二个矩阵与该元素列号相同的元素，两两相乘后再求和。

array([[ 28.,  64.],
       [ 67., 181.]])

In [16]:
 x1 = np.arange(6).reshape((2, 3))

In [17]:
x1

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
x2 = np.arange(3, 9).reshape((2, 3))

In [21]:
x2

array([[3, 4, 5],
       [6, 7, 8]])

In [23]:
x1 * x2       #NumPy中的*是矩阵逐元素乘积

array([[ 0,  4, 10],
       [18, 28, 40]])

In [25]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [27]:
x @ np.ones(3)     #特殊符号@也作为中缀操作符，用于点乘矩阵的操作

array([ 6., 15.])

In [11]:
from numpy.linalg import inv, qr  #numpy.linalg拥有一个矩阵分解的标准函数集，以及其他常用函数，例如求逆和行列式求解

In [12]:
X = np.random.randn(5, 5)

In [13]:
mat = X.T.dot(X)    #X.T.dot(X)计算的是X和它的转置矩阵X.T的点乘积

In [14]:
inv(mat)            #inv计算方阵的逆矩阵

array([[ 4.02837469,  2.62135614,  5.78716946, 10.44560159,  1.76621611],
       [ 2.62135614,  1.94615322,  3.8908566 ,  6.81997313,  1.21276941],
       [ 5.78716946,  3.8908566 , 12.18804183, 18.34659063,  3.74892757],
       [10.44560159,  6.81997313, 18.34659063, 30.62836479,  5.51589453],
       [ 1.76621611,  1.21276941,  3.74892757,  5.51589453,  1.24655161]])

In [21]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.91059231e-15, -5.08346514e-15,
        -5.80510021e-15,  5.70503638e-16],
       [-9.87471531e-16,  1.00000000e+00,  3.11279842e-15,
         1.53191703e-15, -5.51739263e-16],
       [ 4.01995275e-15, -2.68094140e-16,  1.00000000e+00,
        -2.31452360e-15, -1.39068519e-18],
       [-1.63528086e-16,  2.24551589e-15, -1.22454527e-15,
         1.00000000e+00, -1.10850598e-16],
       [ 4.53273466e-15,  4.28715690e-16,  7.61909019e-15,
         1.54393803e-14,  1.00000000e+00]])

In [22]:
q, r = qr(mat)

In [23]:
r

array([[-8.80305445,  4.32735931, -6.05947967,  4.2865938 ,  7.73120349],
       [ 0.        , -3.62144761, -4.39964991,  1.78421421,  9.2508141 ],
       [ 0.        ,  0.        , -3.28005264,  0.40861562,  8.59822088],
       [ 0.        ,  0.        ,  0.        , -0.38915417,  2.08567841],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.14054738]])

In [24]:
#伪随机数生成   它们是由具有确定性行为的算法根据随机数生成器中的随机数种子生成的。

In [41]:
samples = np.random.normal(size = (4, 4))    #使用normal生成一个4x4的正态分布样本

In [42]:
samples

array([[ 0.86371729, -0.12209157,  0.12471295, -0.32279481],
       [ 0.84167471,  2.39096052,  0.07619959, -0.56644593],
       [ 0.03614194, -2.0749776 ,  0.2477922 , -0.89715678],
       [-0.13679483,  0.01828919,  0.75541398,  0.21526858]])

In [43]:
np.random.seed(1234)     #更改随机数种子

In [50]:
rng = np.random.RandomState(1234)      #numpy.random中的数据生成函数公用一个全局随机数种子。
                                       #可以使用RandomState()生成一个随机数生成器，使数据独立于其他的随机数状态

In [52]:
rng.randn(10)

array([-0.15323616, -2.43250851,  0.50798434, -0.32403233, -1.51107661,
       -0.87142207, -0.86482994,  0.60874908,  0.5616381 ,  1.51475038])

In [54]:
#随机漫步   从0开始，步进为1和-1，且两种步进发生的概率相等。

In [55]:
nsteps = 1000

In [64]:
draws = np.random.randint(0, 2, size=nsteps)

In [66]:
steps = np.where(draws > 0, 1, -1)

In [69]:
walk = steps.cumsum()

In [70]:
walk

array([  1,   0,  -1,   0,   1,   2,   1,   2,   1,   0,   1,   2,   3,
         4,   5,   6,   7,   8,   7,   8,   9,   8,   7,   6,   5,   4,
         3,   4,   3,   2,   3,   2,   1,   0,  -1,   0,  -1,   0,  -1,
        -2,  -3,  -2,  -3,  -4,  -3,  -4,  -3,  -2,  -3,  -2,  -3,  -2,
        -1,  -2,  -3,  -4,  -3,  -2,  -3,  -2,  -3,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   6,   5,   6,   5,   6,
         7,   8,   9,  10,   9,  10,  11,  12,  13,  14,  15,  14,  15,
        14,  13,  14,  13,  14,  13,  12,  11,  10,   9,   8,   9,  10,
         9,  10,  11,  10,   9,   8,   9,   8,   7,   8,   9,  10,  11,
        10,  11,  10,  11,  10,   9,   8,   9,  10,  11,  12,  13,  14,
        13,  14,  15,  14,  13,  14,  13,  14,  13,  14,  15,  16,  15,
        16,  15,  14,  13,  14,  13,  14,  15,  16,  17,  16,  17,  18,
        19,  20,  21,  20,  19,  18,  17,  16,  17,  18,  17,  16,  15,
        14,  13,  12,  13,  14,  13,  12,  11,  12,  13,  12,  1

In [62]:
walk.min()

-24

In [63]:
walk.max()

54

In [72]:
(np.abs(walk) >= 10).argmax()     #abs逐元素的计算整数，浮点数，复数的绝对值      argmax可以返回布尔值数组中最大值的第一个位置(True就是最大值)

81

In [73]:
#一次性模拟多次随机漫步

In [74]:
nwalks = 5000

In [75]:
nsteps = 1000

In [76]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))     #每一行相当于一次1000的随机漫步

In [77]:
steps = np.where(draws > 0, 1, -1)

In [78]:
walks = steps.cumsum(1)

In [79]:
walks

array([[  1,   0,  -1, ...,  22,  21,  20],
       [  1,   2,   1, ..., -36, -35, -34],
       [  1,   0,   1, ..., -28, -27, -28],
       ...,
       [  1,   2,   3, ...,  18,  17,  18],
       [ -1,   0,   1, ...,  10,  11,  10],
       [ -1,  -2,  -3, ..., -22, -23, -24]], dtype=int32)

In [80]:
walks.max()

126

In [86]:
walks.min()

-119

In [ ]:
#计算出30或-30的最小穿越时间

In [83]:
hists30 = (np.abs(walks) >= 30).any(1)    #any函数用于判断给定参数是否全部为 False，则返回 False，如果有一个为 True，则返回 True

In [84]:
hists30

array([ True,  True,  True, ..., False, False,  True])

In [85]:
hists30.sum()

3341

In [88]:
crossing_times = (np.abs(walks[hists30]) >= 30).argmax(1)   #walks[hists30]根据布尔值索引选择True行

In [89]:
crossing_times.mean()     #均值

502.46662675845556

In [93]:
#可以用其他分布实验随机漫步，如normal，再根据特定的均值和标准差即可生成正态分布下的随机步：

In [95]:
nwalks = 100

In [ ]:
nsteps = 50

In [102]:
steps_normal = np.random.normal(loc = 0, scale = 0.25, size = (nwalks, nsteps))

In [103]:
steps_normal

array([[-0.21047013,  0.08070815, -0.17326207, ..., -0.22225633,
        -0.24694141, -0.23833937],
       [-0.05210968,  0.20461712,  0.21266715, ...,  0.37476414,
         0.40162073, -0.1314355 ],
       [-0.12735862,  0.00628026,  0.10211408, ...,  0.65484838,
        -0.03590127, -0.135724  ],
       ...,
       [ 0.32410342,  0.26040217, -0.00755745, ..., -0.28040491,
         0.08726762,  0.54625957],
       [-0.79548504, -0.18020523,  0.03449911, ...,  0.2169641 ,
         0.24733847, -0.36095224],
       [-0.34677602, -0.321942  , -0.42359548, ...,  0.30463516,
         0.1280777 , -0.54632592]])

In [104]:
steps_normal = np.where(steps_normal > 0, 1, -1)

In [105]:
steps_normal

array([[-1,  1, -1, ..., -1, -1, -1],
       [-1,  1,  1, ...,  1,  1, -1],
       [-1,  1,  1, ...,  1, -1, -1],
       ...,
       [ 1,  1, -1, ..., -1,  1,  1],
       [-1, -1,  1, ...,  1,  1, -1],
       [-1, -1, -1, ...,  1,  1, -1]])

In [106]:
walks = steps_normal.cumsum(1)

In [107]:
walks

array([[ -1,   0,  -1, ..., -14, -15, -16],
       [ -1,   0,   1, ...,  18,  19,  18],
       [ -1,   0,   1, ...,  34,  33,  32],
       ...,
       [  1,   2,   1, ...,   8,   9,  10],
       [ -1,  -2,  -1, ...,  52,  53,  52],
       [ -1,  -2,  -3, ...,   0,   1,   0]], dtype=int32)