In [2]:
#数组转置和换轴

In [1]:
import numpy as np

In [4]:
arr = np.arange(15).reshape((3, 5))

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
arr.T        #T为数组的转置属性(适用于一二维数组)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [7]:
arr = np.random.randn(6, 3)

In [8]:
arr

array([[-0.95238766,  0.2492741 ,  1.00684147],
       [ 1.0902498 , -0.89804452, -0.18440344],
       [ 0.79775471, -1.12779415,  0.13228578],
       [-0.40417517, -1.14000887,  2.69562716],
       [-0.72518665,  2.12217058,  1.17950344],
       [ 0.36720328, -0.96506918,  1.52543592]])

In [9]:
np.dot(arr.T, arr)      #计算矩阵内积（矩阵乘）

array([[ 3.55619094, -3.54878459, -2.43913822],
       [-3.54878459,  8.87512789, -1.77469171],
       [-2.43913822, -1.77469171, 12.04982278]])

In [2]:
arr = np.arange(16).reshape((2, 2, 4))

In [3]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [4]:
arr.transpose((1, 0, 2))      #原维度顺序为（0,1,2）现在改为（1,0,2）  原数组确定4的位置为（0,1,0）更换后变为（1，0,0）  返回为视图

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [10]:
arr.swapaxes(1, 2)   #将1，2维度交换，4的位置010更换为001    返回为视图

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [ ]:
#通用函数：快速的逐元素数组函数

In [21]:
arr = np.arange(10)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.sqrt(arr)      #计算每个元素的平方根

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [24]:
np.exp(arr)   #计算每个元素的自然指数值e**x

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [25]:
x = np.random.randn(8)

In [26]:
y = np.random.randn(8)

In [27]:
x

array([-0.63271247,  0.12935178, -0.71589714, -1.50515428, -0.65743146,
       -0.86332213,  0.49912522, -0.85763674])

In [28]:
y

array([ 0.29410082, -0.41974576,  0.04650321, -2.21340731, -1.1270452 ,
       -1.33262382, -0.21634411,  0.1859354 ])

In [29]:
np.maximum(x,y)       #逐个元素地将x和y中的元素最大值计算出来

array([ 0.29410082,  0.12935178,  0.04650321, -1.50515428, -0.65743146,
       -0.86332213,  0.49912522,  0.1859354 ])

In [30]:
arr = np.random.randn(7) * 5

In [37]:
arr

array([-1.82779521, -5.20020206, -2.83366936,  4.31428914,  2.27398051,
        4.95252994, -1.18566017])

In [32]:
remainder, whole_part = np.modf(arr)     #返回一个浮点值数组的小数部分和整数部分

In [33]:
remainder

array([-0.82779521, -0.20020206, -0.83366936,  0.31428914,  0.27398051,
        0.95252994, -0.18566017])

In [34]:
whole_part

array([-1., -5., -2.,  4.,  2.,  4., -1.])

In [40]:
np.sqrt(arr)

G:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan, 2.07708669, 1.50797232,
       2.22542804,        nan])

In [41]:
arr

array([-1.82779521, -5.20020206, -2.83366936,  4.31428914,  2.27398051,
        4.95252994, -1.18566017])

In [42]:
np.sqrt(arr, arr)     #通用函数接收一个可选参数out，允许对数组按位置操作（即可以原地修改）

G:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan, 2.07708669, 1.50797232,
       2.22542804,        nan])

In [43]:
arr

array([       nan,        nan,        nan, 2.07708669, 1.50797232,
       2.22542804,        nan])

In [44]:
#使用数组进行面向数组编程

In [58]:
points = np.arange(-5, 5, 1)

In [59]:
points

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [63]:
xs, ys = np.meshgrid(points, points)#返回的第一个数组为以第一个参数数组为行，第二个参数数组列数为行数的数组。
                                    #第二个数组为以第二个参数数组的转置为列，第一个参数的列数数为列数的数组。

In [61]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [64]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [65]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [66]:
z

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

In [67]:
import matplotlib.pyplot as plt

In [16]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values");
plt.imshow(z, cmap=plt.cm.gray);
plt.colorbar()

NameError: name 'plt' is not defined

In [ ]:
#将条件逻辑作为数组操作

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [5]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [6]:
cond = np.array([True, False, True, True, False])

In [7]:
result = np.where(cond, xarr, yarr)

In [8]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
arr = np.random.randn(4, 4)

In [10]:
arr

array([[ 0.61559788, -0.46675238,  1.34031213, -1.14103436],
       [-0.11257956, -1.64302402, -2.31063466, -1.92370022],
       [ 0.10280939,  1.42875152, -2.51736304, -1.18764732],
       [ 0.62138073, -1.8226286 ,  1.88827634, -1.45812958]])

In [12]:
np.where(arr > 0, 2, -2)     #将正值替换为2，负值替换为-2

array([[ 2, -2,  2, -2],
       [-2, -2, -2, -2],
       [ 2,  2, -2, -2],
       [ 2, -2,  2, -2]])

In [15]:
np.where(arr > 0, 2, arr)      #将所有正值替换为常数2

array([[ 2.        , -0.46675238,  2.        , -1.14103436],
       [-0.11257956, -1.64302402, -2.31063466, -1.92370022],
       [ 2.        ,  2.        , -2.51736304, -1.18764732],
       [ 2.        , -1.8226286 ,  2.        , -1.45812958]])

In [ ]:
#数学和统计方法

In [17]:
arr = np.random.randn(5, 4)

In [18]:
arr

array([[ 1.13623618,  0.97498376,  0.54687074,  0.27476385],
       [ 0.50303013,  1.52473522, -0.68993824, -0.28784537],
       [-0.32669892,  0.41888068, -1.23973176, -0.13318748],
       [-0.38354021, -0.43229015, -0.08240859,  1.14171169],
       [ 2.65994244, -2.74227477,  0.59409462, -0.74509834]])

In [20]:
arr.mean()      #数学平均

0.135611774652254

In [22]:
arr.sum()   #计算所有元素的累和

2.7122354930450796

In [23]:
arr.mean(axis = 1)     #mean，sum等函数可以接受axis参数，0为行轴，1为列轴

array([ 0.73321363,  0.26249544, -0.32018437,  0.06086819, -0.05833401])

In [24]:
arr.sum(axis = 0)

array([ 3.58896962, -0.25596525, -0.87111323,  0.25034436])

In [38]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
arr.cumsum()      #从0开始元素累计和

array([ 0,  1,  3,  6, 10, 15, 18, 22, 27, 33, 40, 48], dtype=int32)

In [42]:
arr = np.array([[0, 1, 2], [3, 4, 5], [3, 4, 5], [6, 7, 8]])

In [43]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 6,  9, 12],
       [12, 16, 20]], dtype=int32)

In [45]:
arr.cumprod(axis = 1)    #从1开始元素累积积

array([[  0,   0,   0],
       [  3,  12,  60],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)