In [2]:
import numpy as np

In [7]:
data = np.random.randn(2, 3)  #符合正态分布的随机数

In [10]:
data

array([[-0.39661904, -2.19538266,  0.8136524 ],
       [ 0.13155406, -1.12918323,  1.08015465]])

In [11]:
data.shape

(2, 3)

In [22]:
data.dtype

dtype('float64')

In [24]:
data.ndim

2

In [30]:
data1 = [6, 7.5, 8, 9.0, 0, 1]

In [31]:
arr1 = np.array(data1)

In [32]:
arr1

array([6. , 7.5, 8. , 9. , 0. , 1. ])

In [38]:
data2 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [39]:
arr2 = np.array(data2)

In [40]:
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
arr2.shape

(2, 2, 2)

In [2]:
np.arange(15)  #arange为Python内建函数range的数组版

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr3 = np.array([1.3, 2.4, 3.5], dtype=np.float64)    #dtype指定数据类型

In [12]:
arr3.dtype

dtype('float64')

In [15]:
arr3

array([1.3, 2.4, 3.5])

In [16]:
int_arr3 = arr3.astype(np.int32)  #astype更改数据类型,()内也可以为类型代码或者其他数组.dtype属性

In [17]:
int_arr3.dtype

dtype('int32')

In [18]:
int_arr3

array([1, 2, 3])

In [21]:
arr4 = np.array([[1, 2, 3],[4, 5, 6]])

In [22]:
arr5 = np.array([[3, 2, 1],[2, 7, 6]])

In [24]:
arr5 > arr4  #同尺寸数组比较产生一个布尔值数组

array([[ True, False, False],
       [False,  True, False]])

In [37]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5:8]

array([5, 6, 7])

In [70]:
arr_slice = arr[5:8]

In [71]:
arr_slice

array([ 5, 12,  7])

In [72]:
arr_slice[1] = 10

In [73]:
arr_slice

array([ 5, 10,  7])

In [75]:
arr          #数组的切片为原数组的视图，与复制不同，任何对于视图的修改都会反映到原数组上   如需切片的拷贝则需要调用copy函数如：arr[5:8].copy

array([ 0,  1,  2,  3,  4,  5, 10,  7,  8,  9])

In [3]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])

In [4]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3d[1, 0]

array([7, 8, 9])

In [23]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2d[:2, 1:]   #前面为行，后面为列

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[:2, 1:] = 0

In [38]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [34]:
data = np.random.randn(7, 4)

In [36]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [33]:
data

array([[ 1.45552762, -0.34026945, -0.14501641,  0.95957789],
       [-1.43769028, -1.2972494 , -0.42754331,  0.53884861],
       [ 1.35857761, -1.01872187,  0.92017971, -1.24865449],
       [ 0.79104039,  0.91815138,  0.76894105, -0.92469632],
       [ 1.31855088,  0.5923139 ,  2.28071073,  0.37771182],
       [ 1.17007079,  0.51575842, -0.18186357,  0.27288885],
       [-0.01418359,  0.22325925, -0.63512201,  0.11535648]])

In [39]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [41]:
data[names == 'Bob']     #布尔索引(索引为复制数组)

array([[-0.73477574,  0.22242394,  1.68329623,  0.80118884],
       [ 1.16828639, -0.11267936,  0.38755432,  0.24192717]])

In [46]:
data[names == 'Bob', 2:]

array([[1.68329623, 0.80118884],
       [0.38755432, 0.24192717]])

In [47]:
names !=  'Bob'      #!或~都为取反

array([False,  True,  True, False,  True,  True,  True])

In [48]:
data[~(names == 'Bob')]

array([[ 0.90735361,  1.41265874,  0.42935464, -0.97395054],
       [-0.75369416,  0.15601758, -1.75695816, -0.38619657],
       [-0.43668247, -1.41981577, -1.83879029,  0.69009433],
       [-0.22615028, -0.70009578,  0.6510553 , -0.4535282 ],
       [-0.34650865, -0.30951568, -1.78646494,  0.25571869]])

In [49]:
cond = names == 'Bob'

In [55]:
data[~cond] = 1

In [56]:
data

array([[-0.73477574,  0.22242394,  1.68329623,  0.80118884],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.16828639, -0.11267936,  0.38755432,  0.24192717],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ]])

In [57]:
mask = (names == 'Bob')| (names == 'Will')         #and和or对布尔值数组无效，需要使用&(and)和|(or)代替

In [58]:
mask

array([ True, False,  True,  True,  True, False, False])

In [59]:
arr = np.empty((8, 4))   #神奇索引(索引为复制数组)

In [61]:
for i in range(8):
    arr[i] = i

In [62]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [63]:
arr[[4, 3, 0 ,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [64]:
arr[[-3, -5, -7]]           #负索引将从尾部进行选择

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [65]:
arr = np.arange(32).reshape((8, 4))

In [66]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [67]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [68]:
#通过选择矩阵中行列的子集形成矩形区域的一种方法

In [70]:
arr[[1, 5, 7, 2]] [:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])