In [2]:
import numpy as np

In [2]:
#布尔值数组的方法

In [3]:
arr = np.random.randn(100)

In [5]:
(arr > 0).sum()     #正值的个数（布尔值会被强制为1（True）和0（False））

55

In [6]:
bools = np.array([False, False, True, False])

In [7]:
bools.any()   #检查数组中是否至少有一个True（可以用于非布尔值数组，所有非0元素按True处理）

True

In [8]:
bools.all()   #检查数组是否每个值都是True（可以用于非布尔值数组，所有非0元素按True处理）

False

In [9]:
#排序

In [3]:
arr = np.random.randn(6)

In [4]:
arr

array([ 0.60596391,  0.44689441,  0.92912102, -0.48485667, -0.23287829,
        1.62845544])

In [5]:
arr.sort()      #按位置排序

In [6]:
arr

array([-0.48485667, -0.23287829,  0.44689441,  0.60596391,  0.92912102,
        1.62845544])

In [16]:
arr = np.random.randn(5, 3)

In [18]:
arr

array([[ 0.26004561, -1.11745632, -0.77516108],
       [-0.84583488, -0.45449066,  0.80015403],
       [ 0.72674807,  1.10753834,  0.58579508],
       [-0.54375187,  0.0647146 ,  0.49627467],
       [ 0.74642818, -1.38329548, -1.74004751]])

In [20]:
np.sort(arr)   #顶层np.sort方法返回的是数组拷贝

array([[-1.11745632, -0.77516108,  0.26004561],
       [-0.84583488, -0.45449066,  0.80015403],
       [ 0.58579508,  0.72674807,  1.10753834],
       [-0.54375187,  0.0647146 ,  0.49627467],
       [-1.74004751, -1.38329548,  0.74642818]])

In [21]:
arr

array([[ 0.26004561, -1.11745632, -0.77516108],
       [-0.84583488, -0.45449066,  0.80015403],
       [ 0.72674807,  1.10753834,  0.58579508],
       [-0.54375187,  0.0647146 ,  0.49627467],
       [ 0.74642818, -1.38329548, -1.74004751]])

In [22]:
arr.sort(1)    #可以传递axis，按轴向排序

In [23]:
arr

array([[-1.11745632, -0.77516108,  0.26004561],
       [-0.84583488, -0.45449066,  0.80015403],
       [ 0.58579508,  0.72674807,  1.10753834],
       [-0.54375187,  0.0647146 ,  0.49627467],
       [-1.74004751, -1.38329548,  0.74642818]])

In [26]:
large_arr = np.random.randn(10)     #计算数组的分位数，并选出对应值

In [27]:
large_arr

array([-0.45212629,  0.52657923,  0.8287912 , -0.74869361, -0.73642258,
       -1.57709275, -1.04254178,  2.11679248,  0.17053856,  2.69407834])

In [28]:
large_arr[int(0.05 * len(large_arr))]    # %5分位数（quantile）

-0.4521262873994649

In [29]:
#唯一值与其他集合逻辑

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [32]:
np.unique(names)   #返回唯一值排序后形成的数组

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [33]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [34]:
np.unique(ints)

array([1, 2, 3, 4])

In [35]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [36]:
np.in1d(values, [2, 3, 6])    #检查一个数组中的值是否在另外一个数组中，并返回一个布尔值数组

array([ True, False, False,  True,  True, False,  True])

In [37]:
#使用数组进行文件输入输出

In [38]:
arr = np.arange(10)

In [39]:
np.save('some_array', arr)     #默认后缀为.npy

In [40]:
np.load('some_array.npy') 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr1 = np.arange(5)

In [43]:
arr2 = np.arange(6, 10)

In [44]:
np.savez('array_archive.npz', a=arr1, b=arr2)      #使用savez并将数组作为参数传递给函数，用于在未压缩文件中保存多个数组

In [45]:
arch = np.load('array_archive.npz')    #当载入时，获得一个字典型对象

In [48]:
arch['a']

array([0, 1, 2, 3, 4])

In [47]:
arch['b']

array([6, 7, 8, 9])

In [51]:
np.savez_compressed('arrays_compressed.npz', a=arr1, b=arr2)    #如果数据已经压缩，可以使用此方法将数据存入已经压缩的文件