In [2]:
#数组转置和换轴

In [3]:
import numpy as np

In [4]:
arr = np.arange(15).reshape((3, 5))

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
arr.T        #T为数组的转置属性(适用于一二维数组)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [7]:
arr = np.random.randn(6, 3)

In [8]:
arr

array([[-0.95238766,  0.2492741 ,  1.00684147],
       [ 1.0902498 , -0.89804452, -0.18440344],
       [ 0.79775471, -1.12779415,  0.13228578],
       [-0.40417517, -1.14000887,  2.69562716],
       [-0.72518665,  2.12217058,  1.17950344],
       [ 0.36720328, -0.96506918,  1.52543592]])

In [9]:
np.dot(arr.T, arr)      #计算矩阵内积（矩阵乘）

array([[ 3.55619094, -3.54878459, -2.43913822],
       [-3.54878459,  8.87512789, -1.77469171],
       [-2.43913822, -1.77469171, 12.04982278]])

In [10]:
arr = np.arange(16).reshape((2, 2, 4))

In [11]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])