In [13]:
import pandas as pd

In [15]:
import numpy as np

In [5]:
#算数和数据对齐

In [6]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [7]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [8]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [9]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [10]:
s1 + s2      #如果存在某个索引对不相同，则返回结果的索引将是索引对的并集。
             #没有交叠的标签位置上，内部数据对齐会产生缺失值。

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [16]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), 
                   index=['Ohio','Texas', 'Colorado'])

In [17]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), 
                   index=['Utah', 'Ohio','Texas', 'Oregon'])

In [18]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [19]:
df2                #行和列都会执行对齐

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [20]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [21]:
df1 = pd.DataFrame({'A' : [1, 2]})

In [22]:
df2 = pd.DataFrame({'B' : [3, 4]})

In [23]:
df1

A
0  1
1  2

In [24]:
df2

B
0  3
1  4

In [25]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [26]:
#使用填充值的算数方法

In [27]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns = list('abcd'))

In [28]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns = list('abcde'))

In [29]:
df2.loc[1, 'b'] = np.nan

In [30]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [31]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [33]:
df1 + df2        #产生AN值

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [34]:
df1.add(df2, fill_value = 0)      #将缺失值对象填充为0

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [35]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [37]:
df1.div(1)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [38]:
df1.rdiv(1)       #带r的算数方法表示翻转

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [40]:
df1.reindex(columns = df2.columns, fill_value = 0)   #重建索引时，也可以指定填充值

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [41]:
#DataFrame和Series间的操作

In [42]:
arr = np.arange(12.).reshape((3 ,4))

In [43]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [44]:
arr[0]

array([0., 1., 2., 3.])

In [45]:
arr - arr[0]           #减法在每一行都进行了操作。这就是广播机制。

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [46]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [47]:
series = frame.iloc[0]

In [48]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [49]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [51]:
frame - series     #将Series的索引和DataFrame的列进行匹配，并广播到各行

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [52]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])

In [53]:
series2

b    0
e    1
f    2
dtype: int64

In [66]:
frame + series2          #如果一个索引值不在DataFrame的列中，或不在Series的索引中，则对象会重建索引并形成联合

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [56]:
series3 = frame['d']

In [57]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [58]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [70]:
frame.sub(series3, axis = 'index')            #在行上匹配，在列上进行广播。axis匹配轴，index==0。

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0